lib{asio}: {hxx ixx}{upstream/asio/include/**}

# Build options.
#
cxx.poptions =+ "-I$out_base" "-I$src_base/upstream/asio/include"

# Export options.
#
lib{asio}:
{
  cxx.export.poptions = "-I$out_base" "-I$src_base/upstream/asio/include"
}

# Install into the asio/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
upstream/asio/include/
{
  {hxx ixx}{*}:
  {
    install         = include/
    install.subdirs = true
  }
}
